config/routes.rb
Paperboard::Application.routes.draw do

  namespace :settings do
    get 'profile' => 'profile#index'
    patch 'profile' => 'profile#update'

    get 'account' => 'account#index'
    patch 'account' => 'account#update'
    delete 'account' => 'account#destroy'

    get 'organizations' => 'organizations#index'
    delete 'organizations/:id' => 'organizations#leave', as: :leave_organizations

    get 'billing' => 'billing#index'
    post 'billing/subscribe/:plan_id' => 'billing#subscribe', as: :billing_subscribe
    delete 'billing/subscribe' => 'billing#delete_subscription', as: :billing_subscribe_delete
  end

  namespace :v1, format: :json do
    get 'suggestions/people' => 'suggestions#people'
  end

  # User
  resources :users, only: [:show]

  # Organizations
  resources :organizations, module: 'organizations' do
    member do
      get 'members' => 'organizations#members'
      delete 'members/:user' => 'organizations#remove_member', as: :remove_member

      namespace :settings do
        get 'billing' => 'billing#index'
      end
    end

    collection do
      get 'join/:key' => 'organizations#join_team', as: :join_team
    end

    resources :teams do
      member do
        post 'members' => 'teams#add_member', as: :add_member
        delete 'members/:member' => 'teams#remove_member', as: :remove_member
        delete 'invite/:key' => 'teams#remove_invite', as: :remove_invite
      end
    end
  end

  # Projects
  resources :projects, module: 'projects' do
    resources :invites do
      collection do
        get 'accept/:key' => 'invites#accept', as: :accept
      end
    end

    resources :members
    resources :stories
  end

  # Login/Logout sessions
  get 'login'  => 'auth#login', as: :login
  get 'logout' => 'auth#logout', as: :logout
  post 'login'  => 'auth#login'
  match 'forgot-password' => 'auth#forgot_password', via: [:get, :post], as: :forgot_password
  match 'reset-password/:id/:request_token' => 'auth#reset_password', via: [:get, :patch], as: :reset_password

  # User Signup
  match 'signup' => 'auth#signup', via: [:get, :post], as: :signup
  get 'signup/complete' => 'auth#signup_complete', as: :signup_complete
  get 'signup/confirm/:id/:key' => 'auth#signup_confirm_email', as: :signup_confirm_email

  # Generic root url (dashboard) for logged in users
  get 'projects' => 'projects/projects#index', as: :dashboard

  # Custom error routes
  get '404', to: 'errors#404'
  get '422', to: 'errors#422'
  get '500', to: 'errors#500'

  root 'website#index'

end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Organization < ActiveRecord::Base
  include Subscriptions

  has_many :teams, dependent: :destroy
  has_many :members, through: :teams
  has_many :users, -> { uniq }, through: :members
  has_many :projects, dependent: :destroy

  after_create :create_default_teams
  class_attribute :creator
  validates :name, null: false, presence: true

  after_save -> do
    users.each { |u| u.touch }
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def self.new_with_user(params, user)
    self.creator = user
    new params
  end

  def remove_user(user)
    success = user.team_memberships.where(team_id: teams).destroy_all
    destroy if members.size == 0
    success
  end

  private
  def create_default_teams
    team = Team.create! name: 'Owners', role: 'owner', organization: self
    team.members.create! role: 'admin', user: creator
  end
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  organization_id :integer
#  created_at      :datetime
#  updated_at      :datetime
#  members_count   :integer          default(0)
#  role            :string(255)
#

class Team < ActiveRecord::Base
  belongs_to :organization
  validates_inclusion_of :role, in: %w(owner admin standard)

  has_many :members, foreign_key: :team_id, class_name: :TeamMember, dependent: :destroy
  has_many :invites, foreign_key: :team_id, class_name: :TeamInvite, dependent: :destroy

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def is_admin?
    role == 'owner' || role == 'admin'
  end

  def can_be_deleted?
    role != 'owner'
  end
end

app/controllers/organizations/organizations_controller.rb
class Organizations::OrganizationsController < ApplicationController
  include OrganizationLoading

  before_action :load_organization, except: [:index, :new, :create]
  before_action :is_admin, only: [:members, :show]
  before_action :require_admin, only: [:update, :destroy, :remove_member]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = @current_user.cached_organizations
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new_with_user(organization_params, @current_user)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: "Organization #{@organization.name} was successfully created." }
        format.json { render action: 'show', status: :created, location: @organization }
      else
        format.html { render action: 'new' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: "Organization #{@organization.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: "Organization #{@organization.name} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def members
    @users = @organization.users
  end

  def remove_member
    user = User.select(:id, :full_name).find(params[:user])
    if @organization.remove_user(user)
      if user == @current_user
        redirect_to organizations_path, notice: "You just left the organization #{@organization.name}."
      else
        redirect_to members_organization_path(@organization), notice: "#{user.full_name} was successfully removed from the organization #{@organization.name}."
      end
    else
      redirect_to members_organization_path(@organization), alert: "We couldn't do that. Please try later."
    end
  end

  def join_team
    invite = TeamInvite.where(key: params[:key]).pending.first
    return redirect_to(organizations_path) unless invite

    if invite.accept_with_user(@current_user)
      redirect_to invite.team.organization, notice: "You joined team #{invite.team.name} of #{invite.team.organization.name}."
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
  def organization_params
    params.require(:organization).permit(:name)
  end
end

app/controllers/organizations/settings/billing_controller.rb
class Organizations::Settings::BillingController < ApplicationController
  include OrganizationLoading

  before_action :set_plans, only: [:index]
  before_action :load_organization, only: [:index]
  before_action :require_admin

  def index
  end

  private
  def set_plans
    @plans = Plan.all
  end
end

app/controllers/organizations/teams_controller.rb
class Organizations::TeamsController < ApplicationController
  include OrganizationLoading

  before_action :load_organization
  before_action :is_admin
  before_action :require_admin, except: [:index, :show]
  before_action :set_team, except: [:index, :new, :create]

  protect_from_forgery except: [:add_member]

  # GET /teams
  # GET /teams.json
  def index
    @teams = @organization.teams
  end

  # GET /teams/new
  def new
    @team = Team.new role: 'standard'
  end

  # GET /teams/1/edit
  def edit
  end

  def show
    @members = @team.members.includes(:user)
    @members.sort_by! { |m| m.user.full_name }
    @invites = @team.invites.pending.includes(:sender)
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)
    @team.organization = @organization

    respond_to do |format|
      if @team.save
        # Sets the admin to the current user
        @team.members.create role: 'admin', user: @current_user

        format.html { redirect_to organization_team_path(@organization, @team), notice: "Team #{@team.name} was successfully created." }
        format.json { render action: 'show', status: :created, location: @team }
      else
        format.html { render action: 'new' }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: "Team #{@team.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    unless @team.can_be_deleted?
      return redirect_to organization_teams_path(@organization), alert: 'You cannot delete this team.'
    end

    @team.destroy
    respond_to do |format|
      format.html { redirect_to organization_teams_path(@organization), notice: "Team #{@team.name} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def add_member
    data = {}

    if params[:email]
      # Search by user email
      user = User.where(email: params[:email]).first
    elsif params[:user]
      # Search by user id
      user = User.find params[:user]
    end

    if user
      # Adds the user straight to the team
      if @team.members.where(user: user).size == 0
        if @team.members.create(role: 'member', user: user)
          data[:notice] = "#{user.full_name} has been added to the #{@team.name} team."
        end
      else
        data[:alert] = "#{user.full_name} is already part of the #{@team.name} team."
      end
    elsif params[:email]
      # Create the invite
      invite = @team.invites.build(
                                     email: params[:email],
                                     sender: @current_user
      )

      if invite.save
        # Send an email invitation
        if OrganizationMailer.invite_to_team(invite, @team, @current_user, params[:email]).deliver
          data[:notice] = "An invite to join #{@team.name} team has been sent to #{params[:email]}"
        else
          invite.destroy
          data[:alert] = 'Could not send the email. Please try later.'
        end

      else
        data[:alert] = "#{invite.errors.full_messages.join('. ')}."
      end
    end

    redirect_to organization_team_path(@organization, @team), data
  end

  def remove_member
    member = TeamMember.includes(:user).where(id: params[:member], team: @team).first
    if member and member.destroy
      if member.user == @current_user
        redirect_to organization_team_path(@organization, @team), notice: "You just left the team #{@team.name}."
      else
        redirect_to organization_team_path(@organization, @team), notice: "#{member.user.full_name} was successfully removed from the team #{@team.name}."
      end
    else
      redirect_to organization_team_path(@organization, @team), alert: 'The member specified does not exist.'
    end
  end

  def remove_invite
    @team.invites.find(params[:key]).destroy
    redirect_to organization_team_path(@organization, @team), notice: 'The invite has been deleted.'
  end

  private
  def set_team
    @team = Team.where(organization: @organization, id: params[:id]).first

    redirect_to organization_teams_path(@organization), alert: 'The team does not exist.' unless @team
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def team_params
    params.require(:team).permit(:name, :role)
  end
end

app/controllers/settings/organizations_controller.rb
class Settings::OrganizationsController < ApplicationController
  include OrganizationLoading

  before_action :load_organizations, only: [:index]
  before_action :load_organization, only: [:leave]

  def index
  end

  def leave
    if @organization.remove_user(@current_user)
      flash.notice = "You left the organization #{@organization.name}"
      redirect_to action: 'index'
    end
  end

  private
  def load_organizations
    @organizations = @current_user.cached_organizations
  end
end

app/views/organizations/teams/_form.html.slim
= form_for @team, url: organization_teams_path(@organization) do |f|
  - if @team.errors.any?
    #error_explanation
      h2 = "#{pluralize(@team.errors.count, "error")} prohibited this team from being saved:"
      ul
        - @team.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name, "Team name"
    = f.text_field :name, placeholder: 'e.g. Developers, Designers'
    hr

  .field
    p What permission level should this team have?
    div
      ' Owners
      = f.radio_button :role, "admin", disabled: true
      p Owners have full access to all projects and have admin rights to the organization. You can only have one team of this kind.
    div
      ' Admin access
      = f.radio_button :role, "admin"
      p This team will be able to manage teams and their projects (useful for Project Managers)
    div
      ' Standard access
      = f.radio_button :role, "standard"
      p This team will only be able to view its projects.
    hr

  .actions = f.submit 'Create team'

app/views/organizations/teams/edit.html.slim
h1
  ' Editing team:
  = @team.name

== render 'form'

app/views/organizations/teams/index.html.slim
= render "organizations/header"

h2 Teams

table border=1 cellpadding=6 cellspacing=0
  tr
    th Name
    th Members
    th Actions

  - @teams.each do |team|
    tr
      td = link_to team.name, organization_team_path(@organization, team)
      td = pluralize(team.members_count, 'member')
      td
        - if @is_admin && team.can_be_deleted?
          = link_to 'Delete team', organization_team_path(@organization, team), :method => :delete

- if @is_admin
  hr
  = link_to 'New Team', new_organization_team_path

app/views/organizations/teams/new.html.slim
= render "organizations/header"

h1 New team

== render 'form'

app/views/organizations/teams/show.html.slim
= render "organizations/header"

h2
  ' Team:
  = @team.name

= link_to 'Team settings', edit_organization_team_path(@organization, @team)

hr

- if @team.is_admin?

  p Owners have full access to all projects and have admin rights to the organization.
  p Owners can change billing info and cancel organization accounts.

table border=1 cellpadding=6 cellspacing=0
  thead
    th User
    th Role
    th Joined
    th

  - @members.each do |member|
    tr
      td = member.user.full_name
      td = member.role
      td = time_ago_in_words(member.created_at) + " ago"
      td
        - if @is_admin
          - lbl = member.user.id != @current_user.id ? 'Remove' : 'Leave'
          = link_to lbl, remove_member_organization_team_path(@organization, @team, member), :method => :delete

- if @invites.length > 0
  hr
  h3 Pending invites

  table border=1 cellpadding=6 cellspacing=0
  thead
    th Sent by
    th
    th Email
    th

  - @invites.each do |invite|
    tr
      td = invite.sender.full_name
      td = time_ago_in_words(invite.created_at) + " ago"
      td = invite.email
      td
        - if @is_admin
          = link_to "Delete", remove_invite_organization_team_path(@organization, @team, invite), :method => :delete

- if @is_admin
  hr
  h3 Add member
  .suggestions data-source=v1_suggestions_people_path(format: :html)
    input placeholder="Name or email" type="text" data-post=add_member_organization_team_path(@organization, @team) data-accept="email"