config/routes.rb
Paperboard::Application.routes.draw do

  namespace :settings do
    get 'profile' => 'profile#index'
    patch 'profile' => 'profile#update'

    get 'account' => 'account#index'
    patch 'account' => 'account#update'
    delete 'account' => 'account#destroy'

    get 'organizations' => 'organizations#index'
    delete 'organizations/:id' => 'organizations#leave', as: :leave_organizations

    get 'billing' => 'billing#index'
    post 'billing/subscribe/:plan_id' => 'billing#subscribe', as: :billing_subscribe
    delete 'billing/subscribe' => 'billing#delete_subscription', as: :billing_subscribe_delete
  end

  namespace :v1, format: :json do
    get 'suggestions/people' => 'suggestions#people'
  end

  # User
  resources :users, only: [:show]

  # Organizations
  resources :organizations, module: 'organizations' do
    member do
      get 'members' => 'organizations#members'
      delete 'members/:user' => 'organizations#remove_member', as: :remove_member

      namespace :settings do
        get 'billing' => 'billing#index'
      end
    end

    collection do
      get 'join/:key' => 'organizations#join_team', as: :join_team
    end

    resources :teams do
      member do
        post 'members' => 'teams#add_member', as: :add_member
        delete 'members/:member' => 'teams#remove_member', as: :remove_member
        delete 'invite/:key' => 'teams#remove_invite', as: :remove_invite
      end
    end
  end

  # Projects
  resources :projects, module: 'projects' do
    resources :invites do
      collection do
        get 'accept/:key' => 'invites#accept', as: :accept
      end
    end

    resources :members
    resources :stories
  end

  # Login/Logout sessions
  get 'login'  => 'auth#login', as: :login
  get 'logout' => 'auth#logout', as: :logout
  post 'login'  => 'auth#login'
  match 'forgot-password' => 'auth#forgot_password', via: [:get, :post], as: :forgot_password
  match 'reset-password/:id/:request_token' => 'auth#reset_password', via: [:get, :patch], as: :reset_password

  # User Signup
  match 'signup' => 'auth#signup', via: [:get, :post], as: :signup
  get 'signup/complete' => 'auth#signup_complete', as: :signup_complete
  get 'signup/confirm/:id/:key' => 'auth#signup_confirm_email', as: :signup_confirm_email

  # Generic root url (dashboard) for logged in users
  get 'projects' => 'projects/projects#index', as: :dashboard

  # Custom error routes
  get '404', to: 'errors#404'
  get '422', to: 'errors#422'
  get '500', to: 'errors#500'

  root 'website#index'

end

app/controllers/organizations/settings/billing_controller.rb
class Organizations::Settings::BillingController < ApplicationController
  include OrganizationLoading

  before_action :set_plans, only: [:index]
  before_action :load_organization, only: [:index]
  before_action :require_admin

  def index
  end

  private
  def set_plans
    @plans = Plan.all
  end
end

app/controllers/settings/account_controller.rb
class Settings::AccountController < ApplicationController
  before_action :set_user

  def index
  end

  def update
    if @user.update_with_password(user_params)
      @current_user = @user

      flash.now[:notice] = 'Your account was successfully updated.'
    end

    render action: 'index'
  end

  def destroy
    User.find(@current_user).destroy
    redirect_to logout_path
  end

  private
  def set_user
    @user = User.find(@current_user)
    @owns_organizations = @user.teams.where(role: 'admin').count > 0
  end

  def user_params
    params.require(:user).permit(:current_password, :password, :password_confirmation)
  end
end

app/controllers/settings/billing_controller.rb
class Settings::BillingController < ApplicationController
  before_action :set_plans, only: [:index]
  before_action :set_current_subscription

  def index
  end

  def subscribe
    @plan = Plan.find(params[:plan_id])
    @subscription = @plan.subscriptions.build

    if params[:subscription]
      @subscription = @plan.subscriptions.build(subscription_params)
      @subscription.user = User.find(@current_user.id)

      if @subscription.save_with_payment
        redirect_to settings_billing_path, notice: 'Thank you for subscribing!'
      end
    end
  end

  def delete_subscription
    if @current_user.has_active_subscription
      @current_user.subscription.destroy
      redirect_to settings_billing_path, alert: 'Your subscription have been deleted'
    end
  end

  private
  def set_plans
    @plans = Plan.all
  end

  def set_current_subscription
    @subscription ||= @current_user.subscription
  end

  def subscription_params
    params.require(:subscription).permit(:paymill_card_token, :paymill_card_last)
  end
end

app/controllers/settings/organizations_controller.rb
class Settings::OrganizationsController < ApplicationController
  include OrganizationLoading

  before_action :load_organizations, only: [:index]
  before_action :load_organization, only: [:leave]

  def index
  end

  def leave
    if @organization.remove_user(@current_user)
      flash.notice = "You left the organization #{@organization.name}"
      redirect_to action: 'index'
    end
  end

  private
  def load_organizations
    @organizations = @current_user.cached_organizations
  end
end

app/controllers/settings/profile_controller.rb
class Settings::ProfileController < ApplicationController
  before_action :set_user

  def index
  end

  def update
    if @user.update(user_params)
      @current_user = @user

      flash.now[:notice] = 'Your profile was successfully updated.'
    end

    render action: 'index'
  end

  private
  def set_user
    @user = User.find(@current_user)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :avatar)
  end
end

app/helpers/settings/profile_helper.rb
module Settings::ProfileHelper
end

app/views/settings/billing/_available_contexts.html.slim
ul
  li
    a href=settings_billing_path data-context="user" data-left=@current_user.plan("projects_left")
      = image_tag @current_user.avatar.url(:small)
      strong = @current_user.full_name
  - for organization in @current_user.organizations.includes(:subscription, :projects)
    li
      a href=organization_path(organization) data-context="organization" data-id=organization.id data-left=organization.plan("projects_left")
        strong = organization.name

app/views/settings/billing/_current_subscription.html.slim
- if subject.has_active_subscription
  p
    ' You're signed up for
    strong monthly billing
    '  with the
    strong #{I18n.translate("plans.names.#{@subscription.plan.name}")}
    '  plan.
  p
    | Your credit card **** **** **** #{@subscription.paymill_card_last} will automatically be charged #{number_to_currency @subscription.plan.price, unit: "$"} on #{@subscription.expire_at.strftime("%B %d, %Y")}.
  = button_to "Cancel subscription", settings_billing_subscribe_delete_path, method: :delete

- else
  p You don't have any active subscription.

app/views/settings/billing/_plans.html.slim
table class='ui'
  thead
    th Plan name
    th Features
    th Price
    th

  tbody

    - @plans.reverse_each do |plan|

      tr
        td = I18n.translate("plans.names.#{plan.name}")
        td = plan_features plan.name
        td
          = number_to_currency plan.price, unit: "$", precision: 0
          | /month
        td.center
          - if subject.has_active_subscription
            - if subject.subscription.plan.id == plan.id
              | Your plan
            - else
              = button_to (subject.subscription.plan.price > plan.price ? "Downgrade" : "Upgrade"), settings_billing_subscribe_path(plan.id)
          - else
            = button_to "Subscribe", settings_billing_subscribe_path(plan.id)

    tr
      td = I18n.translate("plans.names.free")
      td = plan_features "free"
      td = number_to_currency 0, unit: "$", precision: 0
      td.center
        - if not subject.has_active_subscription
          | Your plan

app/views/settings/billing/index.html.slim
- @title = 'Billing'

.frame.top-margin
  .bit-5
    = render "settings/sidebar"

  .bit-5-4.content
    h2 Account billing

    section.grey
      h3 Billing information
      = render partial: "current_subscription", locals: {subject: @current_user}

    section.grey
      h3 Available plans

      = render partial: "plans", locals: {subject: @current_user}

app/views/settings/billing/subscribe.html.slim
javascript:
  var PAYMILL_PUBLIC_KEY = "#{ENV['PAYMILL_PUBLIC_KEY']}";
= javascript_include_tag "https://bridge.paymill.com/"

- @title = 'Billing'

.frame.top-margin


  .bit-2.offset-4.content
    h2 Subscribe to #{I18n.translate("plans.names.#{@subscription.plan.name}")} plan

    h3 = plan_features @subscription.plan.name

    section.grey
      h3 Credit card billing details

      = form_for @subscription, url: "", html: {class: 'styled full'} do |f|

        = f.hidden_field :paymill_card_token
        = f.hidden_field :paymill_card_last

        .field
          = label_tag :cardholder_name, "Cardholder name"
          .with-icon
            i class='fa fa-user'
            = text_field_tag :cardholder_name, @current_user.full_name, name: :cardholder_name, maxlength: 16

        .field
          = label_tag :card_number, "Credit Card Number"
          .with-icon
            i class='fa fa-credit-card'
            = text_field_tag :card_number, nil, name: nil, maxlength: 16, class: 'number'

        .field
          = label_tag :card_code, "Security Code on Card (CVV)"
          .with-icon
            i class='fa fa-key'
            = text_field_tag :card_code, nil, name: nil, maxlength: 5, class: 'short number'

        .field
          = label_tag :card_month, "Card Expiration"
          = select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"}
          = select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"}

        .field
          = label_tag :null, "Price"
          .with-icon
            i class='fa fa-money'
            = text_field_tag nil, number_to_currency(@subscription.plan.price, unit: "$") + " per month", disabled: true

        p#paymill_error.error
          noscript JavaScript is not enabled and is required for this form. First enable it in your web browser settings.

        - if @subscription.errors.any?
          - @subscription.errors.full_messages.each do |message|
            p.error = message

        .field.actions = f.submit 'Subscribe'